ALTER TABLE Xe ALTER COLUMN tinhtrang NVARCHAR(50);
ALTER TABLE Taixe ALTER COLUMN holot NVARCHAR(50);
ALTER TABLE Taixe ALTER COLUMN ten NVARCHAR(50);
ALTER TABLE Taixe ALTER COLUMN phai NVARCHAR(50);
ALTER TABLE Phancong ALTER COLUMN trangthaichuyen NVARCHAR(50);
ALTER TABLE Phancong ALTER COLUMN diadiemden NVARCHAR(50);
SELECT*FROM Taixe
SELECT*FROM Xe
SELECT*FROM Phancong